### ISSUE TITLE
Fake Enchanted Books?

### ISSUE THREAD

**Issue by MayliSong** [CiscuLog/Survivor-s-Elegy#4] opened 2023-10-15 23:38 UTC
A bunch of people on my personal server suddenly noticed we had nonfunctional enchanted books. Normal functional enchanted books have yellow titles, but these nonfunctional ones have blue titles and cannot be applied to anything other than other enchanted books. Several of us were exploring the Nether recently so we think they must have been looted from Nether Fortresses.
[A link to an imgur album with some screenshots](https://imgur.com/a/ik8PlvP)
The blue enchanted books give no xp when put in a grindstone, and cannot be applied to anything other than other enchanted books. However, they don't [create functional enchanted books](https://imgur.com/a/rRpGads) from this; they just add a seemingly fake enchantment and blue title onto a functional book.
We can't confirm at the moment but assume these must be from the new Nether Fortresses, as another player recently explored a Piglin Crevice and seems to have found functional Soul Speed books. 

Assuming this is a bug, rather than a lore feature? If it is a bug, I'll be replacing any bugged books players find until a better fix is found.

**Comment by CiscuLog** [comment] 2023-10-16 15:47
Hello! This bug was supposedly fixed in version alpha 0.8.3. Are you using any version prior to that one?

The issue is the enchantments books are enchanted themselves, instead of them storing the enchantment.

**Comment by MayliSong** [comment] 2023-10-17 01:25
It seems that I am, could have sworn I was more up to date than that. As long as it won't break anything on the server, I'll update to 0.8.4 right away. Sorry about that, I always feel a bit bad when its such an easy thing like that on my end.

**Comment by CiscuLog** [comment] 2023-10-17 05:57
Don't worry, it was a serious bug after all!

Closing the issue, make sure to replace the bugged books anyway because those won't update

**Closed by CiscuLog** 2023-10-17 05:57 UTC
